### ISSUE TITLE
Unable to upload file to existing experiment

### ISSUE THREAD

**Issue by Ahtenus** [genomizer/genomizer-server#105]
Hi! 
When adding files to an existing experiment we get an
POST http://scratchy.cs.umu.se:7000/file net::ERR_EMPTY_RESPONSE 
as response.

The error on the server is:
May 27, 2014 4:03:45 PM sun.net.httpserver.ExchangeImpl sendResponseHeaders
WARNING: sendResponseHeaders: rCode = 204: forcing contentLen = -1

**Comment by tnaeg** [comment]
Files can be uploaded. Solved!
