### ISSUE TITLE
Genomerelease adds immediately without checking if the files are valid.

### ISSUE THREAD

**Issue by steelmountain** [genomizer/genomizer-server#106]
I talked with Ruaridh about this, but here is it for everyone to see!

when I add genomrelease "ECLIPSE" with the single file eclipse, it is added to the database and I can see it among the other genomereleases. However, the eclipse file does not have an ending, and is rejected by the transfer group. 

It should not be like this, database/api should only accept files that transfer accepts.

**Comment by tnaeg** [comment]
All files are beeing validated. Solved!
