### ISSUE TITLE
Sending multiple genome release files, added succesfully but not showing up?

### ISSUE THREAD

**Issue by steelmountain** [genomizer/genomizer-server#110]
This is the message body I send:
{"genomeVersion":"TEST","specie":"Fly","files":["GVim_Portable_7.1.0.exe","Genomizer.pdf","grupp22-ou2.pdf","grupp22-ou3.pdf","ideaIC-12.1.2.tar.gz"]}

this is the answer from server :

[{"URLupload":"http://scratchy.cs.umu.se:8000/upload.php?path=/var/www/data/genome_releases/Fly/TEST/GVim_Portable_7.1.0.exe"},{"URLupload":"http://scratchy.cs.umu.se:8000/upload.php?path=/var/www/data/genome_releases/Fly/TEST/Genomizer.pdf"},{"URLupload":"http://scratchy.cs.umu.se:8000/upload.php?path=/var/www/data/genome_releases/Fly/TEST/grupp22-ou2.pdf"},{"URLupload":"http://scratchy.cs.umu.se:8000/upload.php?path=/var/www/data/genome_releases/Fly/TEST/grupp22-ou3.pdf"},{"URLupload":"http://scratchy.cs.umu.se:8000/upload.php?path=/var/www/data/genome_releases/Fly/TEST/ideaIC-12.1.2.tar.gz"}]

this is from getGenomeReleases:

[ ...
{"genomeVersion":"TEST","species":"Fly","folderPath":"/var/www/data/genome_releases/Fly/TEST/","files":["GVim_Portable_7.1.0.exe","Genomizer.pdf","grupp22-ou2.pdf","grupp22-ou3.pdf"]},
...
{"genomeVersion":"TEST","species":"Fly","folderPath":"/var/www/data/genome_releases/Fly/TEST/","files":["ideaIC-12.1.2.tar.gz"]},
...
]

Which might be fine and dandy, but it's certainly confusing to see two genome releases with the same name in a table.

When I remove TEST i removed both.

**Comment by tnaeg** [comment]
Tested and should work as intended now.
