### ISSUE TITLE
Fix or delete ignored tests

### ISSUE THREAD

**Issue by 23Skidoo** [genomizer/genomizer-server#138]
I've disabled a bunch of tests that were either erroneous, depended on hardcoded data not included in the repo, were too slow or couldn't be easily fixed. Please take a look and either delete or re-enable them.

Full list of disabled tests:

- [x] `test/server/test/ServerGenomeReleaseTest.java`
- [x] `test/server/test/ServerChainTestClass.java`
- [x] `test/server/test/ServerLoginLogoutTest.java`
- [x] `test/server/test/ServerAnnotationTest.java`
- [x] `test/response/test/GetGenomeReleaseResponseTest.java`
- [x] `test/response/test/AddGenomeReleaseResponseTest.java`
- [x] `test/conversion/test/ProfileDataConverterTest.java`
- [x] `test/database/test/unittests/FileNameValidatorTest.java`
- [x] `test/database/test/unittests/DatabaseAccessorThreadTests.java`
- [x] `test/command/test/GetProcessStatusCommandTest.java`
- [x] `test/command/test/ProcessCommandTest.java`
- [x] `test/response/test/LoginResponseTest.java`

**Comment by 23Skidoo** [comment]
There's also a bunch of unused stuff in `server.test.dummies`.

**Comment by tnaeg** [comment]
BL has fixed the test for us. fixed in #397

**Comment by 23Skidoo** [comment]
All tests mentioned in the original bug report are now fixed/removed. There are some new ignored tests: parts of `RatioCalcTest` and `GenomeReleaseConverterTest` (which I think was fixed by conversion work). Will open new tickets for them.
