### ISSUE TITLE
Attempting to log in causes a null pointer exception in Authenticate on develop

### ISSUE THREAD

**Issue by yakrar** [genomizer/genomizer-server#164]
This seems to be caused by `uuid` being set to `null` in ~~`commandHandler.processNewCommand`~~ `Doorman.handleRequest`, which breaks the call to `Authenticate.getUsernameByID` in `Command.createCommand` later on.

I think. Could someone from server/BL take a look at this?

**Comment by 23Skidoo** [comment]
Fixed. The problem was that `HashMap.get(null)` returns `null`, but `ConcurrentHashMap.get(null)` raises `NullPointerException`. Moral of the story: pervasive nulls are "fun".
