### ISSUE TITLE
Allow authorization token as argument in file download URL

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#185]
Since the web group has found no way to download a file with a GET method and custom HTTP headers, it would be easier to send the token as an argument in the URL instead:

<code>GET /download/[path]&token=[token] HTTP/1.x</code>

**Comment by azoimide** [comment]
To keep up with the planning of the web group, it would be desirable to have this working during 29/4

**Comment by 23Skidoo** [comment]
FWICT downloading works fine in the desktop client. You just do 

```
GET http://hostname/api/download?path=path/to/file

Authorization: your-token
```

Why do we need to special-case the web client?

**Comment by azoimide** [comment]
From what I've found out, AJAX requests cannot save files, and HTML src attributes cannot have custom headers for their GETs. It is possible that there are other ways, but I haven't found one. In my opinion, it would be trivial to check for tokens both in URL and in headers, and if both are present and they differ, a bad request response can be sent.

I'm just exploring the possibilities, but this would be my choice.

**Comment by 23Skidoo** [comment]
OK, sure, I can add this.

**Comment by azoimide** [comment]
Great! We can check again tomorrow and make sure that this would actually work before you waste any time

**Comment by 23Skidoo** [comment]
Should be fixed now. Reopen/ask me if something does not work.

**Comment by azoimide** [comment]
server.Util.parseURI: URI.getQuery returns null
->
server.Doorman.performAuthorization: no "token" key in HashMap

URI:
---
/download&path=/Home/staff/niklasf/edu/pvt/genomizer-web/app/data/test_1/profile/0/bearpurse.txt&token=e2b7f71e-594b-41fc-9634-6f79688f08ba
---

**Comment by tastyburger** [comment]
Note that a query starts with a question mark.

**Comment by tastyburger** [comment]
Refer to the following doc page: http://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getQuery()
Particularly this piece: [scheme:][//authority][path][?query][#fragment]

**Comment by 23Skidoo** [comment]
Yes, should be `/download?path=...`

**Comment by azoimide** [comment]
My mistake, thanks for the hely guys

**Comment by 23Skidoo** [comment]
Just tested on my machine, seems to work.
