### ISSUE TITLE
Wrong URL returned to web client for file upload (develop branch)

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#195]
The returned URL is:
```
https://130.239.192.110:7000/upload?path=/home/designer/Documents/files/Test_1/profile/0/test5.txt
```
But it has to be:
```
https://130.239.192.110/api/upload?path=/home/designer/Documents/files/Test_1/profile/0/test5.txt
```
(This is enforced by apache to protect from XSS)

**Comment by 23Skidoo** [comment]
Probably a configuration error. Change `uploadURL` in `settings.cfg` to `uploadURL = /api/upload?path=` and similarly for `downloadURL`. You may need to pull latest changes from `develop`.

**Comment by 23Skidoo** [comment]
Optimistically closing.

**Comment by azoimide** [comment]
Working for web client if port is set to 443, can't get to work with desktop regardless of port and upload URL. Preferrably the same URL (/api/upload) would be sent to both web and desktop since web can't solve this any other way.

**Comment by azoimide** [comment]
This might be hard to get to work with SSL though, a solution would be to make the clients tell what URL they want to send the file to

**Comment by 23Skidoo** [comment]
We should look at this together tomorrow. If it works in the web client, it should also work with desktop since we don't do anything special in that case.

**Comment by azoimide** [comment]
Forgot to change proxy in CentOS to https, this might be an issue...

**Comment by 23Skidoo** [comment]
I think this is solved, reopen if the problem still exists.

**Comment by azoimide** [comment]
Solved for web at least, desktop seems to have no instinct of self preservation regarding this issue
