### ISSUE TITLE
iptables are reset at reboot

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#200]
(just so I don't forget)

**Comment by knownsoldier** [comment]
1. sed on /etc/sysconfig/iptables-config, both IPTABLES_SAVE_ON_RESTART and IPTABLES_SAVE_ON_STOP to yes.
2. Rules for FORWARD: REJECT all -- anywhere anywhere reject-with icmp-host-prohibited.
3. all weird rules under IN_public_allow

**Comment by knownsoldier** [comment]
Save current table using iptables-save > filename. Can used to manually restore table using iptables-restore < filename if reload after reboot was unsuccessful.

**Comment by tnaeg** [comment]
Fixed
