### ISSUE TITLE
Restructure Raw to profile pipeline

### ISSUE THREAD

**Issue by knownsoldier** [genomizer/genomizer-server#226]
Reading the clients wishes regarding a new pipeline, I've (sort of, if I've understood correctly) parsed these steps. Two new tools are needed, picard (java) and pyicos (python), both are at least downloaded and callable at the moment (although without proper parameters).

--Raw to Profile--
1. Upload .fastq raw data
2. Check .fastq scoring scheme, check_scoring-scheme.pl data.fastq
3. Align .fastq reads with bowtie2, using scheme from previous step and genome release (only one file needed, ratio calc. needs two).
4. Throw away the .fastq file.
5. Results in .sam 
6. Sort .sam file with java -jar SortSam I=<input_file> O=<sorted_file> SO=coordinate
7. Produces .sam file
8. Remove duplicates with java -jar MarkDuplicates INPUT=<sorted_file> OUTPUT=<marked_file> METRICS_FILE=metrics.txt REMOVE_DUPLICATES=true
9. Now has metrics file and marked .sam file
10. Estimate strand cross-correlation with pyicos strcorr, pyicos strcorr <marked>.sam test.pk -f sam -F bed_pk
11. Generate .wig with extended reads, pyicos convert <marked>.sam <extended_marked>.wig -f sam -F bed_wig -O -x 303
12. Profile data in .wig format produced, processing done.

Smoothing, step and ration calculation is to be done separately. It should be a choice if .sam files are saved or not during the process.

**Comment by 23Skidoo** [comment]
Current status: mostly done, needs to be integrated.

**Comment by knownsoldier** [comment]
Current status: Probably done, integrated but might produce faulty .wig files. Currently examining.

**Comment by 23Skidoo** [comment]
I think this is done. Please reopen if disagree.
