### ISSUE TITLE
Invalid characters - filenames

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#249]
Filenames everywhere ( experiments, files, genomereleses... ) cannot use special characters.
Even trying to delete an experiment with such signs in the name gives: 
```` 400:
{"message":"Invalid characters in experiment name. Valid characters are: ^, A-Z, a-z, 0-9, space, _ and ."}
```

This is not great.

**Comment by 23Skidoo** [comment]
Which special characters should be allowed?

**Comment by rednatto** [comment]
I think some of the scientists files included '-', really don't know ?
That is not really the main part though; we should either way be able to delete all files/experiments which we find in the database.

**Comment by Mintey** [comment]
Mostly a problem with allowing space in names. When transmitted in the JSON body, the space is kept as a space, but when transmitted in the header (such as in delete), the space is not kept as a space, but rather changed into something else, which makes the server not find the proper file/experiment

**Comment by 23Skidoo** [comment]
`FileValidator` checks for `-\w,\s\.åäöÅÄÖ()`. So whitespace and dashes seem to be allowed?

> , the space is not kept as a space, but rather changed into something else, which makes the server not find the proper file/experiment

"Something else" is `%20`, see http://en.wikipedia.org/wiki/Percent-encoding
To decode, just use `URLDecoder.decode`:

```
scala> java.net.URLDecoder.decode("foo%20bar", "utf-8")
res1: java.lang.String = foo bar
```

**Comment by azoimide** [comment]
I had this problem when my DB tables weren't updated to match the server version

**Comment by johannes-ekman** [comment]
The characters allowed through BL are now: "A-Z, a-z, 0-9, -, _ and .". Whitespace has been removed, "-" has been added. This includes both removal and adding files. This issue should therefore be fixed, or is there still a file you are unable to delete?

**Comment by timqy** [comment]
Agreed
