### ISSUE TITLE
Wierd error messages on annotation modification

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#250]
````400: {"message":"The value freetext does not exist in FREETEXTTEST and can not be deleted"}````
Could you instead perhaps say "*Cannot be deleted due to being default*", or maybe "*... because it is being used*". Is this our message, or why would it say *does not exist* ?

**Comment by rednatto** [comment]
Someone changed this?

**Comment by rednatto** [comment]
(For freetext the still seem weierd.)

**Comment by tastyburger** [comment]
Did a quick lookup, it seems that the annotation cannot be deleted because it does not exist in the database. Try to submit the values then retrieve them to make sure they entered the database. Then send a deletion request and if the problem persists, get back to us.

**Comment by rednatto** [comment]
Could you check how the freetext bit is handeled in the database, this still seems wierd for us!

**Comment by rednatto** [comment]
Stefan fixed alot of stuff. Now only DB group needs to fix their default test annots.

**Comment by timqy** [comment]
is this still an issue ?

**Comment by rednatto** [comment]
Donno, I think it is fix'd.

**Comment by yakrar** [comment]
@rednatto In that case I'm closing this. Feel free to reopen it if the problem persists.
