### ISSUE TITLE
Cache timestamp breaks stuff

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#254]
?annotations=[expid] works fine but ?annotations=[expid]&_=12345 doesn't.
Since the server doesn't cache, cache time stamps could just be thrown away.

**Comment by azoimide** [comment]
Receving "Invalid characters in experiment name. Valid characters are: ^, A-Z, a-z, 0-9, space, _ and ."
Commit: 4932dcd

**Comment by 23Skidoo** [comment]
> `?annotations=[expid] works fine but ?annotations=[expid]&_=12345`

What is the full URL?

**Comment by azoimide** [comment]
Couldn't reproduce since login fails due to some cache error, will try again later

**Comment by azoimide** [comment]
Request:
`
/experiment/Test_1?_=1431694621108
`
Response:
400
`
{"message":"Invalid characters in experiment name. Valid characters are: ^, A-Z, a-z, 0-9, space, _ and ."}
`

**Comment by 23Skidoo** [comment]
Should be fixed now.

**Comment by azoimide** [comment]
Request:
`
/search/?annotations=test_1[expid]&_=1431700554881
`
Response:
400
`
{"message":"Could not create a command from request. Bad format on request."}
`
Server version: 81075c6

**Comment by 23Skidoo** [comment]
`SearchCommand` apparently expects a parameter: `search/foo[expID]`.

**Comment by 23Skidoo** [comment]
Search should work now.

**Comment by tnaeg** [comment]
Searching with an empty string dosn't work. Time stamp stays.

**Comment by azoimide** [comment]
Request:
`/experiment/ExpSmall?_=1432106084555`
Response: 400
`{"message":"Could not create a command from request. Bad format on request."}`
Server version: c67ac47

**Comment by tastyburger** [comment]
Does `GET /experiment/ExpSmall` also return that error? Why is it necessary to supply a timestamp?

**Comment by 23Skidoo** [comment]
#288 probably fixes this.

**Comment by 23Skidoo** [comment]
Verified that this works in `develop`, added a fix to the Postman test suite (63c3d12b8312ffad5d7194ba79fcc55be213a702).
