### ISSUE TITLE
Typo in new API URI

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#259]
`
/process/cancelproccess
`
should be
`
/process/cancelprocess
`

**Comment by 23Skidoo** [comment]
Looks like a documentation bug.

**Comment by tastyburger** [comment]
There seems to be a discrepancy between the API page and the implementation. The actual implementation of the process cancellation is `DELETE /process` and I believe they retrieve the process id via the request body.

**Comment by tnaeg** [comment]
API is fixed.
