### ISSUE TITLE
Requests to get process statuses are pending

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#262]
Request:
`
/process/?_=1431701788406
`
No response (pending in browser)

Server debug output:
```
-----------------
NEW EXCHANGE: GET /process/?_=1431701788411
Trying to authenticate token 4419be34-025f-4bf4-8583-1db515b52ce0...
User testuser authenticated successfully.
Request body: 

END OF EXCHANGE
------------------
```
Server version: 81075c6

**Comment by 23Skidoo** [comment]
I'll look at this during the weekend.

**Comment by azoimide** [comment]
This was my fault when trying to create a dummy list

**Comment by tastyburger** [comment]
Does the id in `/process/?_=id` denote the process id? Because it seems that there is no support for retrieving the status of an individual process. Currently, the statuses of all processes are retrieved and sent.

**Comment by azoimide** [comment]
The underscore key in the query denotes a cache time stamp and has nothing to do with the actual API. I managed to get back a dummy list as well, see issue 264.

**Comment by tnaeg** [comment]
Closing again seems to have been reopened unnecessary.
