### ISSUE TITLE
Bug in getting response from GetProcessStatusResponse body

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#264]
`response.GetProcessStatusResponse:42`
`if (getProcessStatuses.size() > 0) {`
should be
`if (getProcessStatuses.size() == 0) {`?
Server version: 60bbf33

**Comment by tastyburger** [comment]
Fixed.

**Comment by azoimide** [comment]
I'm not sure how this is supposed to work, so don't trust me about the fix. Didn't fully understand why there were a length check in the first place.

**Comment by tastyburger** [comment]
Me neither. The response body should indicate the absence of processes and the log message should not be so severe. Nevertheless, have this as a temporary solution and somebody should soon make a more constructive message out of this.

**Comment by tastyburger** [comment]
Thought several people could be assigned to this issue. Whatever people, just somebody take a look at this.

**Comment by azoimide** [comment]
In my opinion, it's up to the clients to handle the message if the list is empty.

**Comment by 23Skidoo** [comment]
Looks like the fix is correct. Returning an empty list when there're no processes makes sense.

**Comment by tastyburger** [comment]
The response body was changed to an empty json list and it's now working properly. An empty string caused client timeouts.
