### ISSUE TITLE
Trying to create a new, but already existing, experiment gives bad error message.

### ISSUE THREAD

**Issue by oi12mlw** [genomizer/genomizer-server#272]
Creating a new experiment with an already existing experiment ID gives response code 500 and the message 'Adding of experiment <expID> didn't work due to temporary problems with the database.'

The message should give a more detailed explanation of the error.

**Comment by currybullen** [comment]
Pull request pending for this issue.

**Comment by 23Skidoo** [comment]
This is fixed in `develop`.
