### ISSUE TITLE
Delete tuple from database after bowtie

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#290]
When bowtie has finished running the raw files are deleted from disk, but not from the database. They are still visible as part of the experiment.

**Comment by tastyburger** [comment]
Is it the absolute file path that gets stored in the db?

**Comment by tastyburger** [comment]
Fixed in ee441e1.

**Comment by tnaeg** [comment]
Close the issue if fix is implemented in develop

**Comment by tastyburger** [comment]
Should be closed only after it's been verified by the clients that it's working as intended.

**Comment by yakrar** [comment]
Status on this?

**Comment by azoimide** [comment]
This should be done as of 21094b5
