### ISSUE TITLE
Unclear error message responses

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#308]
Getting 500 (internal server error)
"Error when deleting genome release <name> for specie <specie>. Database error"
On a **DELETE /genomeRealese/<species>/<version>**

**Comment by tnaeg** [comment]
Is it miss spelled in program or is it miss spelled in the issue?

**Comment by tastyburger** [comment]
That error message is issued when there is an IO or a database error. Just resend the request.

**Comment by 23Skidoo** [comment]
[Here's the relevant part of the code.](https://github.com/genomizer/genomizer-server/blob/03a8457f3cda7e9fa730d4d30783f82f2d3605dd/src/command/genomerelease/DeleteGenomeReleaseCommand.java#L78) Error 500 seems correct in this case. How do you want the message to be changed?

**Comment by rednatto** [comment]
This is a bit old, but what I wondered was *why* it would show that. An error message like this to me means either that something on serverside has gone very wrong, or that the message is bad in that i still do not know what happened/how to fix the problem.
**It looks like you have changed the messages though / I can't reproduce**

**Comment by timqy** [comment]
fixed in #368
