### ISSUE TITLE
File cleanup utility cannot delete all temporary folders after a process execution

### ISSUE THREAD

**Issue by tastyburger** [genomizer/genomizer-server#318]
The problem could be due to a process holding a file stream that is not closed at the time file cleanup utility is called.

**Comment by 23Skidoo** [comment]
What's the status of this?

**Comment by tastyburger** [comment]
I've not seen any such error logs anymore. Perhaps it was caused by something else that got fixed. I started working on it in FileDeleteFix branch but have ignored for a while it due to other duties. The logs should though be monitored closely in case this problem arises again.

**Comment by 23Skidoo** [comment]
Optimistically closing, reopen if it happens again (preferably with instructions on how to reproduce).
