### ISSUE TITLE
File size stored as a string plus it's not working as intended

### ISSUE THREAD

**Issue by tastyburger** [genomizer/genomizer-server#320]
File size is a numeric value and hence should be treated so. Storing it as a string is quite inefficient as it has to be converted back and forth when upload and retrieving a file. Also, actually it's not working at all. File size shown is zero.

**Comment by tastyburger** [comment]
In the database, it's declared as `FileSize VARCHAR(32) DEFAULT 'N/A'`. Seems also that, most of the time, the size is not updated in the database.

**Comment by 23Skidoo** [comment]
And please use a `BIGINT`, not a 32-bit integer, since we potentially can have >4GB files.

**Comment by unicornmaster** [comment]
Im on it. We will fix the type and research why we get 0 filesize!

**Comment by unicornmaster** [comment]
And we're done! (I think) we have tested it on our vagrant and seems to work, Note that it is currently only implemented for files that are uploaded manually.
