### ISSUE TITLE
Upload fails due "Problems with database"

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#340]
NEW EXCHANGE: POST /file
Trying to authenticate token cd05d365-fba8-4ee6-92d3-d78e4a7f9c7a...
User testuser authenticated successfully.
Request body: 
 {"fileName":"test2.fastq","type":"Raw","author":"testuser","uploader":"testuser","grVersion":"GenomV1","metaData":"default","experimentID":"teasd"}
Adding of file test.fastq to experiment teasd didn't work, reason: Bad value for type long : N/A
Response body: 
{"message":"Adding of file test.fastq to experiment teasd didn't work because of temporary problems with database."}

END OF EXCHANGE
------------------
Adding of file test2.fastq to experiment teasd didn't work, reason: Bad value for type long : N/A
Response body: 
{"message":"Adding of file test2.fastq to experiment teasd didn't work because of temporary problems with database."}

END OF EXCHANGE

on commit: 1aed4bfd715d687415cfbf7f1b28f3b53cc98172

**Comment by 23Skidoo** [comment]
You may need to regenerate the database, the schema changed recently.

**Comment by tastyburger** [comment]
Login to the database using `psql -U <username> -p <port> -h <server>` where the server is currently localhost then run the following `\i drop_all_tables.sql` and `\i genomizer_database_tables.sql` after that.

**Comment by Palledaman** [comment]
Thanks!
