### ISSUE TITLE
Processing status is empty

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#344]
Processing status sends empty body even if bowtie is running.

d1901b191df0306e436e1661c9f6134b2a0d3ede

**Comment by tastyburger** [comment]
Fixed in ff346142785ab922cbda117bbc9e8781bb191f16.

**Comment by tastyburger** [comment]
Further changes made in 1aec14e712b37416a9ba5e1a75948395624a0e89.
