### ISSUE TITLE
Return readable filesize

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#348]
Better if the server return a readable filesize instead of bytes? Like this:

if (size < 1024) {
                return  (size.toFixed(2).toString() + " B");
            } else if (size < 1048576) {
                return ((size / 1024).toFixed(2).toString() + " KiB");
            } else if (size < 1073741824) {
                return ((size / 1048576).toFixed(2).toString() + " MiB");
            } else if (size < 1099511627776) {
                return ((size / 1073741824).toFixed(2).toString() + " GiB");
            } else {
                return ((size / 1099511627776).toFixed(2).toString() + " TiB");
            }

**Comment by tastyburger** [comment]
Copy that code and put it in the client.
