### ISSUE TITLE
Cannot upload large files to production environment (~10GB)

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#366]
Tested with both desktop and web, nothing in error log or debug output.
Server version: c2200861824abd15616ae2fd12128682075eda78

**Comment by 23Skidoo** [comment]
Looking into it.

**Comment by tnaeg** [comment]
Any core dump?

**Comment by azoimide** [comment]
Not that I know of, but if there is, it's still there

**Comment by 23Skidoo** [comment]
Seems to work in my testing. See that you have enough disk space in `/tmp` and on the partition where you put the uploaded files. Can also be a bug in the client.

**Comment by 23Skidoo** [comment]
Saimon thinks it's something with the Apache configuration.

**Comment by azoimide** [comment]
@skriez

**Comment by 23Skidoo** [comment]
We think that this can be solved by appending `KeepAlive=on` to the `ProxyPass` line in `proxy.conf`. See http://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de

**Comment by 23Skidoo** [comment]
Basically, the problem is that it takes some time to copy the downloaded file from `/tmp` to the destination, so Apache thinks that the genomizer server has died and returns error 502. The file is actually uploaded successfully.

**Comment by azoimide** [comment]
Can you fix?

**Comment by 23Skidoo** [comment]
We have changed the upload code to return a response sooner, will do a PR after testing a bit more.
