### ISSUE TITLE
Response at GR upload

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#378]
What does this response message mean for when uploading GR files.
Run on develob branch version from this morning.

Note that it is run on server *...4434...*, and that the upload adress specifies *4433*.
Is this correct? The upload then seems to fail at bad gateway.

````
-----------------
NEW EXCHANGE: POST /genomeRelease
command.genomerelease.PostGenomeReleaseCommand
Trying to authenticate token f4419dbd-e013-4e9a-8034-a3e1642b6e99...
User testadmin authenticated successfully.
Request body: 
 {"genomeVersion":"hej","specie":"xyz","files":["d_melanogaster_fb5_22.1.ebwt"]}
Response body: 
[{"URLupload":"https://130.239.192.110:4433/api/upload?path=/data/genome_releases/xyz/hej/d_melanogaster_fb5_22.1.ebwt"}]
END OF EXCHANGE
------------------
````

**Comment by 23Skidoo** [comment]
> Note that it is run on server ...4434..., and that the upload adress specifies 4433.

Looks like your server is misconfigured. Set `wwwTunnellPort` to 4434 in `settings.cfg`.

**Comment by 23Skidoo** [comment]
We fixed this for you, restart your server.

**Comment by 23Skidoo** [comment]
> The upload then seems to fail at bad gateway.

This is the same as #366, for which we have a fix that is being tested.
