### ISSUE TITLE
Vagrant: /tmp and /data are on different partitions

### ISSUE THREAD

**Issue by 23Skidoo** [genomizer/genomizer-server#381]
```
$ mount
[...]
/dev/sdb2 on / type ext4 (rw,relatime,seclabel,data=ordered)
[...]
/dev/sda1 on /Data type ext4 (rw,relatime,seclabel,data=ordered)
[...]
```

This means that uploaded files have to be copied, which takes a long time if the file in question is large. If /tmp was on the same partition as /data, they could be just renamed instead.

**Comment by skriez** [comment]
Actually, /tmp is on the same partition as /data. As shown by the vagrant configuration file

```ruby
  config.vm.synced_folder "/Data/production-data", "/data"
  config.vm.synced_folder "/Data/production-tmp", "/tmp"
```

The output is you posted is of the root server, and not inside the virtual environment

**Comment by 23Skidoo** [comment]
I'll try to fix this in a different way.

**Comment by 23Skidoo** [comment]
I've added a new option to `ServerSettings` to set the location of file upload temp directory.
