### ISSUE TITLE
Possible to add files with same name to experiment

### ISSUE THREAD

**Issue by knownsoldier** [genomizer/genomizer-server#401]
This results in some problems in i.e. process pipe but the current behavior doesn't follow common sense or standards (two files with the same name on the same path is a no-go.). 

Should probably be checked by databas, throwing exception when new file is added to an experiment with the same name as an existing file in the same experiment.

**Comment by yakrar** [comment]
This *is* enforced in the database:

```.sql
CREATE TABLE File
(
 /* ... */
Path VARCHAR(1024) UNIQUE NOT NULL,
 /* ... */
);
```

**Comment by tnaeg** [comment]
Can I get some more information, is this still a problem? Is it Front-end (BL) or is it back-end (Data Storage)

**Comment by yakrar** [comment]
@tnaeg Does the above edit help?
