### ISSUE TITLE
GET /admin/user JSON

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#407]
Does the JSON thing work?
Is the one at the experimental the one that will be active at lunch?
Is the list of username:username valid JSON?
How is it made to JSON/ How should i parse it?

**Comment by tastyburger** [comment]
The documentation for that part seems to be missing.. According to the code, it looks like this:
[ {"username": "user1"},
{"username": "user2"},
{"username": "user3"} ]

All usernames are retrieved.

**Comment by tnaeg** [comment]
Always check the experimental API aswell on http://docs.genomizerexperimental.apiary.io/#admin it is updated. 

This is a problem since the apiary page is owned by the previous year. So only one person has editorial rights to the page. The experimental is maintained by the current years group.

**Comment by rednatto** [comment]
The API's contained errors, but now seems to have been changed.
Adress is now /admin/userlist
With response { "username":["U1","U2",...]}
( If I understood it correctly. )

The *application/json* should also be changed to the **GET** friendly text version.

**Comment by timqy** [comment]
"fixed #411"
