### ISSUE TITLE
Upload genome release

### ISSUE THREAD

**Issue by c12mbg** [genomizer/genomizer-server#414]
Fungerar inte!

unknown error, error code 502. På desktop får vi tillbaka en html-remsa: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>502 Proxy Error</title></head><body><h1>Proxy Error</h1><p>The proxy server received an invalidresponse from an upstream server.<br />The proxy server could not handle the request <em><a href="/api/genomeRelease">POST&nbsp;/api/genomeRelease</a></em>.<p>Reason: <strong>Error reading from remote server</strong></p></p></body></html>

**Comment by tnaeg** [comment]
The Server is closing the channel, we are looking into it, this has been introduced with a recent merge.

**Comment by timqy** [comment]
Fixed in #426
