### ISSUE TITLE
Error message when logging in

### ISSUE THREAD

**Issue by andreasg92** [genomizer/genomizer-server#417]
If wrong password or username is submitted, an error message comes up with info about "wrong username/password". The error message should not include that info.

**Comment by tastyburger** [comment]
What do you think it should say then? A message indicating that the login credentials are not valid is better than a general message. Also, the message should not indicate whether the username or password is invalid.

**Comment by 23Skidoo** [comment]
IIUC, the problem is that it shows the password that the user has typed.

**Comment by tnaeg** [comment]
This was fixed long ago, please do a pull on your server and see if it still occurs.

**Comment by andreasg92** [comment]
I followed nils's tests v 0.3. Might be outdated.

**Comment by johannes-ekman** [comment]
There was a misunderstanding on our part. This was supposed to have been fixed but it was only semi-fixed. My latest hotfix should be what you are looking for.
