### ISSUE TITLE
Add/Change annotations on existing experiment

### ISSUE THREAD

**Issue by cfladvad** [genomizer/genomizer-server#424]
From Desktop:
When sending a PUT /experiment request with changed annotations. Changes to annotations that does not already exist on experiment is ignored.

May in some way be related to #419 

Assign to: @currybullen
Label: BL

**Comment by tnaeg** [comment]
Same as #369

**Comment by yakrar** [comment]
Err.. is it the same?
This appears to be an issue related to adding annotations/annotation values to an existing experiment, whereas #369 has to do with uploading genome releases. Am I missing something?

**Comment by yakrar** [comment]
Work is being done on this in pr #429 .
