### ISSUE TITLE
Conversion of wig to sgr is wrong

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#464]
The sgr file coordinate should be the rounded average of the two corresponding coordinates in the wig file (any rounding is fine).
A wig line like this:
`chr2L   66      159     1.00`
should be translated to a sgr line like this:
`chr2L   113     1.00`
Now its translated like this:
`chr2L   66     1.00`

**Comment by unicornmaster** [comment]
probably solved in 933b334015a097dabdadfb90904cf4d480ee9a51

**Comment by azoimide** [comment]
Catch me between meeting and lecture and I can check
