### ISSUE TITLE
Smooth file truncated by IGB, should be investigated

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#471]
Check result in Integrated Genome Browser.
Smoothing should use a moving window and compute the mean or median of the window and assign to the rounded (any direction) center coordinate. This can be rewritten in Java with relative ease.

**Comment by 23Skidoo** [comment]
There is a Java implementation of smoothing that doesn't work. It can be enabled by setting `shouldUseJavaSmoothing` to `true` in `settings.cfg`.
