### ISSUE TITLE
Binary file resources/bowtie/bowtie-buildc tracked

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#473]
Should this be tracked? It changes all the time so it pollutes the git statuses

**Comment by 23Skidoo** [comment]
Just add it to `.gitignore`.

**Comment by azoimide** [comment]
Its tracked, should it be removed from tree?

**Comment by 23Skidoo** [comment]
I'm not sure if something will break if I remove it. It's just 2.5K, so better safe than sorry.

**Comment by azoimide** [comment]
@knownsoldier Do you know what it is?
