### ISSUE TITLE
genomizer-server-tester fails nondeterministically on Travis

### ISSUE THREAD

**Issue by 23Skidoo** [genomizer/genomizer-server#475]
Sometimes I see nondeterministic single-test failures in `genomizer-server-tester` tests on Travis ([example](https://travis-ci.org/genomizer/genomizer-server/builds/65365650)) that go away after restarting the build. May be a race condition somewhere - if the issue persists, it can be temporarily papered over by ignoring `genomizer-server-tester`'s exit code. Won't have time to investigate, so it's just FYI.

**Comment by Mintey** [comment]
I have found the error, and it should happen a lot less often, if at all. There was a race-condition between uploading a file and checking that the file existed since the server now responds to the upload before it is moved into place (and thus can be found). Fixed in eb4a787.

**Comment by 23Skidoo** [comment]
Yes, seems to have been fixed. Thanks!
